import { MetricReport, MetricResult, RuleViolation } from '../types/config.interface'

const escape = (value: string): string =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const badge = (label: string): string => `<span class="badge ${label.toLowerCase()}">${label}</span>`

const flagged = (classes: MetricResult[]): MetricResult[] =>
  classes.filter((item) => item.label !== 'OK').sort((a, b) => b.total - a.total)

const metricSection = (report: MetricReport): string => {
  const items = flagged(report.classes)
  if (!items.length) return ''

  const rows = items
    .map((item) => `<tr><td>${badge(item.label)}</td><td>${escape(item.value)}</td><td class="num">${item.total}</td></tr>`)
    .join('')

  return `<section><h2>${report.metric.toUpperCase()}</h2><table><tbody>${rows}</tbody></table></section>`
}

const violationsSection = (violations: RuleViolation[]): string => {
  if (!violations.length) return ''

  const rows = violations
    .map((item) => `<tr><td>${escape(item.from)}</td><td>&rarr; ${escape(item.to)}</td><td>${escape(item.message)}</td></tr>`)
    .join('')

  return `<section><h2>Architecture violations</h2><table><tbody>${rows}</tbody></table></section>`
}

const STYLE = `
  body{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1f2328;background:#fff}
  h1{font-size:1.6rem} h2{font-size:1.1rem;margin-top:2rem;border-bottom:1px solid #eaecef;padding-bottom:.3rem}
  table{width:100%;border-collapse:collapse;font-size:.92rem} td{padding:.4rem .6rem;border-bottom:1px solid #f2f2f2}
  .num{text-align:right;font-variant-numeric:tabular-nums;color:#57606a}
  .badge{font-size:.72rem;font-weight:600;padding:.1rem .45rem;border-radius:999px}
  .warning{background:#fff3cd;color:#7a5b00} .critical{background:#ffe3e0;color:#a1160a} .ok{background:#e6f4ea;color:#1a7f37}
  .summary{color:#57606a} footer{margin-top:2rem;color:#8b949e;font-size:.82rem}
`

export const buildHtmlReport = (report: MetricReport[], violations: RuleViolation[]): string => {
  const findings = report.reduce((sum, metric) => sum + flagged(metric.classes).length, 0) + violations.length
  const sections = [violationsSection(violations), ...report.map(metricSection)].filter(Boolean).join('')
  const body = sections || '<p class="summary">✅ No warnings, criticals or violations.</p>'

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>artie-lens report</title><style>${STYLE}</style></head><body>` +
    `<h1>🔍 artie-lens report</h1>` +
    `<p class="summary">${findings} finding(s) across ${report.length} metric(s).</p>` +
    body +
    `<footer>Generated by artie-lens</footer></body></html>`
}
